version: '3.7'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    depends_on:
      - backend
  backend:
    image: 'mcr.microsoft.com/mssql/server:2019-latest'
    ports:
      - '5000:5000'
    depends_on:
      - db
  db:
    image: 'microsoft/mssql-server-linux'
    environment:
      SA_PASSWORD: 'SuaSenhaDeAcesso'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
